import type { OnPageReport } from "@/serverFunctions/contentOptimization";

/**
 * Turn a scan report into a markdown brief an agent (or writer) can act on
 * directly. Sections with no content are omitted.
 */
export function buildAgentBrief(
  report: OnPageReport,
  pageCategory?: string | null,
): string {
  const opt = report.on_page_optimization;
  const coverage = report.entity_coverage;
  const swipe = report.topic_and_classification.swipe_content;
  const questions = Object.entries(
    report.topic_and_classification.topical_authority_questions,
  ).filter(([, items]) => items.length > 0);
  const internal = report.internal_linking.add_internal_links_from;

  const missing = coverage.natural_language_entities
    .filter((e) => e.coverage_status === "missing")
    .map((e) => e.entity);
  const weak = coverage.natural_language_entities
    .filter((e) => e.coverage_status === "present_not_entity")
    .map((e) => e.entity);
  const missingTerms = coverage.highly_related_terms
    .filter((t) => t.coverage_status === "missing")
    .map((t) => t.entity);
  const missingVariations = coverage.keyword_variations
    .filter((v) => v.coverage_status === "missing")
    .map((v) => v.variation);

  const lines: string[] = [
    `# Content optimization brief: ${report.meta.target_keyword ?? "target keyword"}`,
    "",
    `URL: ${report.meta.url ?? "n/a"}`,
    `Score: ${opt.score ?? "n/a"}/100 (${opt.grade})`,
    "",
    opt.summary,
  ];
  if (pageCategory) {
    lines.push("", `Your page's Google category: ${pageCategory}`);
  }
  const rankingCategories = report.topic_and_classification.page_classification;
  if (rankingCategories.length > 0) {
    lines.push(
      "Ranking page categories: " +
        rankingCategories.map((p) => p.category).join("; "),
    );
  }

  if (opt.focus_areas.length > 0) {
    lines.push("", "## Fix first", ...opt.focus_areas.map((a) => `- ${a}`));
  }
  if (missing.length > 0) {
    lines.push(
      "",
      "## Missing entities (work these into the copy naturally)",
      ...missing.map((e) => `- ${e}`),
    );
  }
  if (weak.length > 0) {
    lines.push(
      "",
      "## Found but needs context (present but weak salience)",
      ...weak.map((e) => `- ${e}`),
    );
  }
  if (missingTerms.length > 0) {
    lines.push(
      "",
      "## Missing highly related terms",
      ...missingTerms.map((t) => `- ${t}`),
    );
  }
  if (missingVariations.length > 0) {
    lines.push(
      "",
      "## Missing keyword variations",
      ...missingVariations.map((v) => `- ${v}`),
    );
  }
  if (swipe.suggested_title) {
    lines.push("", "## Suggested title", swipe.suggested_title);
  }
  if (swipe.topic_coverage.length > 0) {
    lines.push(
      "",
      "## Topics competitors cover that this page skips",
      ...swipe.topic_coverage.map((t) => `- ${t}`),
    );
  }
  if (questions.length > 0) {
    lines.push("", "## Topical authority questions");
    for (const [group, items] of questions) {
      lines.push(`- ${group}:`, ...items.map((q) => `  - ${q}`));
    }
  }
  if (internal.length > 0) {
    lines.push(
      "",
      "## Add internal links from",
      ...internal.map((l) => `- ${l}`),
    );
  }
  lines.push("", "Generated by On-Page.ai via OpenSEO.");
  return lines.join("\n");
}

// ─── Per-section copy text ───────────────────────────────────────────────────

function statusLabel(status: string): string {
  if (status === "missing") return "missing";
  if (status === "present_not_entity") return "found but needs context";
  return "covered";
}

export function buildEntitySectionText(report: OnPageReport): string {
  const coverage = report.entity_coverage;
  const named = new Set(
    coverage.natural_language_entities.map((e) => e.entity),
  );
  const byImportance = [...coverage.natural_language_entities];
  byImportance.sort((a, b) => (b.importance ?? 0) - (a.importance ?? 0));
  const lines = [
    `## Entity coverage: ${report.meta.target_keyword ?? ""}`.trim(),
    `Your density ${coverage.your_url_related_entity_density_score ?? "n/a"} vs competitor avg ${coverage.competitor_related_entity_density_score ?? "n/a"}`,
    "",
    ...coverage.highly_related_terms
      .filter((t) => !named.has(t.entity))
      .map(
        (t) =>
          `- ${t.entity} (high priority, ${statusLabel(t.coverage_status)})`,
      ),
    ...byImportance.map(
      (e) =>
        `- ${e.entity} (importance ${Math.round(e.importance ?? 0)}, ${statusLabel(e.coverage_status)})`,
    ),
  ];
  if (coverage.keyword_variations.length > 0) {
    lines.push(
      "",
      "Keyword variations:",
      ...coverage.keyword_variations.map(
        (v) => `- ${v.variation} (${statusLabel(v.coverage_status)})`,
      ),
    );
  }
  return lines.join("\n");
}

export function buildBenchmarksSectionText(report: OnPageReport): string {
  const rows: Array<[string, number | null, number | null]> = [
    [
      "Words",
      report.benchmarks.your_url.word_count,
      report.benchmarks.page1_average.word_count,
    ],
    [
      "H1",
      report.benchmarks.your_url.h1_count,
      report.benchmarks.page1_average.h1_count,
    ],
    [
      "H2",
      report.benchmarks.your_url.h2_count,
      report.benchmarks.page1_average.h2_count,
    ],
    [
      "H3",
      report.benchmarks.your_url.h3_count,
      report.benchmarks.page1_average.h3_count,
    ],
    [
      "Images",
      report.benchmarks.your_url.image_count,
      report.benchmarks.page1_average.image_count,
    ],
    [
      "Entities",
      report.benchmarks.your_url.entity_count,
      report.benchmarks.page1_average.entity_count,
    ],
    [
      "Keyword variations",
      report.benchmarks.your_url.keyword_variation_count,
      report.benchmarks.page1_average.keyword_variation_count,
    ],
  ];
  return [
    `## Structure vs page-1 average: ${report.meta.url ?? ""}`.trim(),
    "",
    ...rows.map(
      ([label, yours, avg]) =>
        `- ${label}: ${yours ?? "n/a"} (page-1 average ${avg === null ? "n/a" : Math.round(avg)})`,
    ),
  ].join("\n");
}

export function buildCompetitorTermsSectionText(report: OnPageReport): string {
  return [
    `## Competitor term coverage: ${report.meta.target_keyword ?? ""}`.trim(),
    "",
    ...report.competitor_term_coverage.terms.map((term) => {
      const counts = term.competitor_counts;
      const avg =
        counts.length === 0
          ? null
          : counts.reduce((sum, v) => sum + v, 0) / counts.length;
      return `- ${term.keyword}: your count ${term.your_url_count}, competitor avg ${avg === null ? "n/a" : avg.toFixed(1)}`;
    }),
  ].join("\n");
}

export function buildSuggestionsSectionText(report: OnPageReport): string {
  const swipe = report.topic_and_classification.swipe_content;
  const questions = Object.entries(
    report.topic_and_classification.topical_authority_questions,
  ).filter(([, items]) => items.length > 0);
  const lines = [`## Suggestions: ${report.meta.url ?? ""}`.trim()];
  if (swipe.suggested_title) {
    lines.push("", `Suggested title: ${swipe.suggested_title}`);
  }
  if (questions.length > 0) {
    lines.push("", "Topical authority questions:");
    for (const [group, items] of questions) {
      lines.push(`- ${group}:`, ...items.map((q) => `  - ${q}`));
    }
  }
  return lines.join("\n");
}

export function buildInternalLinksSectionText(report: OnPageReport): string {
  const links = report.internal_linking.add_internal_links_from;
  return [
    `## Internal links: ${report.meta.url ?? ""}`.trim(),
    "",
    ...(links.length > 0
      ? ["Add internal links to this page from:", ...links.map((l) => `- ${l}`)]
      : ["No internal link opportunities detected."]),
  ].join("\n");
}

export function buildClassificationSectionText(
  report: OnPageReport,
  pageCategory: string | null,
): string {
  const lines = [
    `## Page Google Category: ${report.meta.url ?? ""}`.trim(),
    "",
    `Your page: ${pageCategory ?? "n/a"}`,
  ];
  const rankingPages = report.topic_and_classification.page_classification;
  if (rankingPages.length > 0) {
    lines.push(
      "",
      "Ranking pages:",
      ...rankingPages.map(
        (p) => `- #${p.rank} ${p.category}${p.url ? ` (${p.url})` : ""}`,
      ),
    );
  }
  return lines.join("\n");
}
